### ISSUE TITLE
Priority between the built-in buttons and the footswitch ?

### ISSUE THREAD

**Issue by MH-guitar** [themaninthesuitcase/KatanaSwitch#1]
Hello,

Having purchased recently a Katana Mk2 50 amp, I've read about your project with great interest. I would consider making a similar project, but using directly a Attiny2313 microcontroller and almost the same schematics as you.

I've got some questions about the priority between the amp built-in buttons and any external footswitch.

- When a footswitch is connected, can we still use the built-in buttons to setup a new configuration and store it in a channel for example ?
- What happens when you select a channel / bank through the built-in buttons, then through a footswitch ?
- Does the amp check the changes of states on the jack to change to another channel / bank ?

Many thanks and best regards from Switzerland.
Marc

**Comment by themaninthesuitcase** [comment]
I'll need to confirm with the amp which is not currently set up but as I recall:

- Yes you can use the amp top buttons, but the foot switch won't know that. To save changes you have to use the amp, the foot switch can't do it.
- If you select say A1 via the foot switch the press B on the amp it will swap at the amp end.  The foot switch can't see this and stays at A1.  If you then press B2 on the foot switch the amp will switch to B2.  Basically "last press wins".
- Not sure what you mean, but the jack input tells the amp what to switch to.  If you set it to "bank A patch 2" then the jack is locked to that and when the amp sees change that it switches.  Then amp will only switch on a change at the jack meaning if you want to use the panel buttons you can and it won't suddenly swap back.  At least that's what I saw when testing as I only tended to use the switch OR the panel, not really both.

**Comment by MH-guitar** [comment]
Hello Chris,

Many thanks for your thorough answers.

Your answer to my 3rd question is exactly what I was considering: the amp doesn't switch back and forth between the channel / bank selected from the footswitch and the ones selected from the buttons.

Best regards.
Marc

**Comment by MH-guitar** [comment]
Hello,
Few weeks ago, I've completed my DIY footswitch for the Katana Mk2 50.
My project has the following features:
* Based on a Attiny 45 microcontroller directly programmed in C, a dual optocoupler to isolate the amp, a couple of resistance and 3 leds.
* A single push button to loop over the banks and channels in the following order: A1, A2, B1, B2.
* 3 leds indicating the status with the same convention as the leds on the amp: 2 leds for channels 1/2, 1 led for bank (off: A, blinking: B).
* Enclosure built with old Mecano parts.
Please find attached pictures of the footswitch and here's a short video showing it: https://youtube.com/shorts/rrMnU0gCXO8?feature=share
Many thanks for having inspiring me to build my own footswitch. Best regards from Switzerland.

Marc-Henri

**Comment by themaninthesuitcase** [comment]
Looks awesome! The AtTiny is probably a much better platform for something like this as it helps keep things small, and it doesn't really need much compute.
