### ISSUE TITLE
There is a simple way to do this.

### ISSUE THREAD

**Issue by infinitekh** [themaninthesuitcase/KatanaSwitch#2]
I saw this project yesterday and was impressed.
However, while working today, I learned about 74hc138d, a 3-to-8 line decoder/demultiplexer.

This project seemed to be exactly the opposite of this, so I looked into it and found that an IC called **74LS148** works in the exact opposite direction.

Since it's just a logic circuit, it seems like some kind of ASIC already existed.

I'm sorry I'm not an English speaker. I got help from Google Translator.

**Comment by themaninthesuitcase** [comment]
I have only skim read the data sheets but I dont think you could. Or at least not without a lot of supporting circuitry to latch each footswitch, transistors to drive the loads etc.  Given the complexity and part count a £3 Arduino is over kill but simple.

**Comment by infinitekh** [comment]
I see. Thank you for your reply. That was beginner's nonsense.
Now that I think about it, you're right.
Excuse me for bothering you.
